- name: Install ZSH
  become: true
  apt: name=zsh
  tags:
    - dotfiles
    - install
    - ssh
    
- name: Change shell to zsh
  become: true
  shell: usermod -s $(which zsh) jafar
  tags:
    - dotfiles
    - install
    - ssh

- name: Install Starship
  shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
  tags:
    - dotfiles
    - install
    - ssh
